language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    
before-script:
    - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS links;'
    - mysql -u root -e 'USE links;'
    - mysql -u root -e 'CREATE TABLE linksmap(shortkey varchar(15) PRIMARY KEY, Link text NOT NULL, visited int(10) DEFAULT 0);
    
script:
  cd public
  phpunit shorten.php
  phpunit redirect.php
